services:
  postgres:
    image: postgres:16.6
    container_name: my_postgres
    env_file:
      - ./env
    volumes:
      - ./postgres/data:/var/lib/postgresql/data
      # - ./postgres/init-scripts:/docker-entrypoint-initdb.d
    ports:
      - "25432:5432"
    restart: unless-stopped
    command:
      - "postgres"
      - "-c"
      - "timezone=Asia/Shanghai"

  redis:
    image: redis:7.4
    container_name: my_redis
    command: redis-server /usr/local/etc/redis/redis.conf
    env_file:
      - ./env
    volumes:
      - ./redis/data:/data
      - ./redis/conf/redis.conf:/usr/local/etc/redis/redis.conf
    ports:
      - "26379:6379"
    restart: unless-stopped

  minio:
    image: minio/minio:RELEASE.2025-01-20T14-49-07Z
    container_name: my_minio
    env_file:
      - ./env
    volumes:
      - ./minio/data:/data
    ports:
      - "29000:9000"  # API 端口
      - "29001:9001"  # Console 端口
    restart: unless-stopped
    command: server /data --console-address ":9001"
