services:
  minio:
    image: minio/minio:RELEASE.2025-01-20T14-49-07Z
    container_name: my_minio
    env_file:
      - ./env
    volumes:
      - ./minio/data:/data
    ports:
      - "29000:9000"  # API 端口
      - "29001:9001"  # Console 端口
    restart: unless-stopped
    command: server /data --console-address ":9001"