services:
  postgres:
    image: postgres:16.6
    container_name: my_postgres
    env_file:
      - ./env
    volumes:
      - ./postgres/data:/var/lib/postgresql/data
      # - ./postgres/init-scripts:/docker-entrypoint-initdb.d
    ports:
      - "25432:5432"
    restart: unless-stopped
    command:
      - "postgres"
      - "-c"
      - "timezone=Asia/Shanghai"